spring.application.name=projectportfolioapi

spring.datasource.url=jdbc:postgresql://localhost:5432/project_portfolio_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
membro.api.url=https://6a0c8a9e5aa893e1015c0b67.mockapi.io/membros

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect